services:

  app:
    build: .
    container_name: rag_app
    ports:
      - "7860:7860"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
      - qdrant
    restart: unless-stopped
  
  redis:
    image: redis/redis-stack:latest
    container_name: redis-db
    ports:
      - "6379:6379"  # The database port
      - "8001:8001"  # RedisInsight (The UI)
    environment:
      - REDIS_ARGS=--maxmemory 512mb --maxmemory-policy volatile-lru
    restart: unless-stopped
  
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-db
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: unless-stopped